# Generated by Django 3.1.2 on 2020-11-25 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for given order', primary_key=True, serialize=False)),
                ('order_date', models.DateField(null=True)),
                ('staff', models.ForeignKey(help_text='Staff that made an order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.staff')),
                ('visitor', models.ForeignKey(help_text='Visitor that made an order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.visitor')),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='id_book',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='id_orders',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.order'),
        ),
    ]
