# Generated by Django 3.1.2 on 2020-12-08 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0002_auto_20201125_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.AlterField(
            model_name='order',
            name='visitor',
            field=models.ForeignKey(help_text='Visitor that made an order', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
