# Generated by Django 3.1.2 on 2020-12-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20201223_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Роман', max_length=100),
            preserve_default=False,
        ),
    ]
