# Generated by Django 3.1.2 on 2020-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_auto_20201223_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True, help_text='Brief information for this author'),
        ),
    ]
