# Generated by Django 3.1.2 on 2020-12-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_auto_20201227_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'description'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='order_items',
            options={'verbose_name': 'Книги в заказе', 'verbose_name_plural': 'Книги в заказах'},
        ),
    ]
